language: python
python:
  - 3.6
install:
- pip install codecov
- pip install -r requirements.txt
- pip install pytest-pep8
before_script:
  - chmod +x setup.py
script:
  - ./setup.py test
after_success:
  - codecov
